name: flutter_live_location_tracker
description: Real-Time Location Tracker App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0

flutter:
  uses-material-design: true
